#!/usr/bin/env python3
"""Build batchUpdate JSON for cld: Hi-Fi History GDoc.

Rewrite of the original "Hi-Fi History — Speakers, Amps and Franken-Builds"
using the cld: pipeline — clean formatting, proper headings, linked references.

Usage:
    python3 build_hifi_history.py | gws docs documents batchUpdate \
        --params '{"documentId": "1jnzCuZmhHWy7XlsAHnEocnS9tj8oveYsHuPAjM9f5Ug"}' \
        --json "$(cat)"
"""

import subprocess
import sys
from datetime import date
from pathlib import Path

# Import DocBuilder from gcp repo
sys.path.insert(0, str(Path.home() / "gcp" / "lib"))
from docbuilder import DocBuilder

REPO_URL = "https://github.com/PeterGrecian/audiolab"


def get_commit_hash():
    return subprocess.check_output(
        ["git", "rev-parse", "HEAD"], text=True
    ).strip()


def footnote(b):
    commit = get_commit_hash()
    short = commit[:7]
    today = date.today().strftime("%-d %B %Y")
    commit_url = f"{REPO_URL}/commit/{commit}"
    b.text("Generated by Claude Code on ", italic=True)
    b.text(today, italic=True)
    b.text(". Source: ", italic=True)
    b.text("audiolab", italic=True, link=REPO_URL)
    b.text(" @ ", italic=True)
    b.text(short, italic=True, link=commit_url)
    b.text(". ", italic=True)
    b.text("Compiled from Google Drive notes (2014\u20132025) and audiolab measurements (2026).", italic=True)
    b.text("\n")


def main():
    b = DocBuilder()

    # Summary
    b.para(
        "A personal record of speakers, amplifiers, crossovers, and builds "
        "accumulated over roughly a decade of home audio experimentation. "
        "From Tannoy Mercury to concrete subwoofers and Python measurement rigs.",
        italic=True
    )
    b.para("")

    # === THE COLLECTION ===
    b.heading("The Collection", 1)

    b.heading("Speakers", 2)

    b.heading("Tannoy Mercury M20", 3)
    b.para(
        "Floor-standing speakers purchased in the 1990s. A cheaper model in the Mercury range. "
        "Scruffy but structurally sound \u2014 sound enough to become the basis "
        "for the franken-speaker project (see below). The Tannoys have been the persistent "
        "backdrop of this whole story."
    )

    b.heading("Rega Ela", 3)
    b.para(
        "Floor-standing, more ambitious than the Tannoys. Both tweeters pushed in, "
        "one bass driver with a voice coil fouling on its magnet. Worth repairing "
        "rather than discarding \u2014 unlike the KEF Coda IIIs (~2007) which met "
        "the same voice coil fate and were thrown away. Mk 2 spec calls for "
        "half-fluted cabinets, four feet, 17cm driver with tweeter. Possibly a Mk 1.5 "
        "sourced from eBay (~\u00a3100)."
    )
    b.para("Tweeter replacement candidates:")
    b.bullet("Scan-Speak Classic D2008/8511 (\u00a340) \u2014 D2008/7203 was the original Rega-spec variant")
    b.bullet("D2008/1100: flatter response at 1\u20132 kHz")
    b.bullet("D2008/1200: extended response above 18 kHz")
    b.bullet("Bass driver: RR125 Rega replacement (\u00a351, rare stock)")

    b.heading("KEF Coda III", 3)
    b.para(
        "Previous pair, ~2007. Voice coil failure. Discarded. "
        "Lesson learned later: voice coils can be re-centred with paper shims, "
        "and WD-40 plus a 20 Hz run-in tone (10W, 10+ hours) can free a sticking coil. "
        "Whether it would have lasted is another question."
    )

    b.heading("Amplifiers", 2)

    b.heading("Yamaha AX-396", 3)
    b.para(
        "2\u00d760W integrated amplifier. ICs include M37478M4-409SP and 2SC4466. "
        "Described in notes as \u201ca bit old, maybe could do better\u201d and with a "
        "hint of nostalgia: \u201cWould I like a Naim Nait again?\u201d. "
        "Last reported location: the loft."
    )

    b.heading("Quad 33 / Quad 303", 3)
    b.para(
        "The Quad 33 pre-amplifier works but \u201csmells bad.\u201d The limitation "
        "is no post-volume-control output \u2014 only a tape output available for "
        "feeding a Pi or USB audio device. A DIY preamp replacement was considered."
    )
    b.para(
        "The Quad 303 is a 60W power amplifier. Status: needs checking \u2014 "
        "oscilloscope inspection, earthing evaluation. Inherently a good amp, just neglected. "
        "Together they formed the backbone of a real hi-fi system for years."
    )

    b.heading("Cambridge Audio A1", 3)
    b.para(
        "25W integrated amplifier \u2014 the most-modified amp in this collection. "
        "Several versions over the years: discrete, then TDA1514 chip amp, "
        "then LM4765 variant (the one owned). NE5532 op-amps with 78L15/79L15 "
        "regulators on \u00b128V unregulated rails, thermally limited to ~50 mA."
    )
    b.para("Planned/completed modifications:")
    b.bullet("Breakout sockets on the preamp output")
    b.bullet("Subwoofer low-pass filter integration (4-pole + 2-pole switchable)")
    b.bullet("Preamp output buffer (unity-gain dual op-amp)")
    b.bullet("PSU investigation for transformer buzz; possible power brick replacement")
    b.para(
        "The headphone output has been used as a preamp output source in a pinch "
        "(fixed gain, but usable)."
    )

    b.heading("Linsley-Hood Class A (1969)", 3)
    b.para(
        "John Laurence Linsley-Hood (9 Feb 1925 \u2013 11 March 2004) published "
        "his classic 10\u201315W Class A design in Wireless World, April 1969, p.148, "
        "with updates in 1996. A Chinese clone board (Banggood, \u00a311) fitted with "
        "2N3055 transistors. Supply 12\u201335V DC; quiescent current 0.3\u20131.8A, "
        "recommended 1.2A \u2014 demands a heatsink over 0.7 kg. "
        "Suited to speakers of 83 dB+ sensitivity with 3\u20138\u201d drivers. Still highly regarded."
    )

    b.heading("Class D Experiments", 3)
    b.para(
        "Several Chinese Class D modules were tried. Verdict: \u201cChinese boards "
        "likely clone components, poor quality, badly designed.\u201d Class D crossover "
        "distortion at low volumes on piano music was initially attributed to the amp, "
        "but later traced to the speakers (as happened with the KEF Coda IIIs). "
        "The KKmoon TPA3116D2 2.1 board found a niche as a subwoofer driver only."
    )
    b.para("")

    # === FRANKEN-SPEAKERS ===
    b.heading("The Franken-Speakers", 1)

    b.heading("The Tannoy Renovation \u2014 June 2017", 2)
    b.para(
        "The defining franken-speaker moment. The Tannoy Mercury M20 cabinets were tired "
        "but structurally sound. Rather than discard them, new drivers were ordered from "
        "Lean Business (lean-business.co.uk), Order #36512, 11 June 2017:"
    )
    b.bullet("Faital Pro 6FE100 \u2014 6\u201d professional full-range midrange (Fs=61 Hz, Re=5.4\u03a9, Vas=14.1L, 100W program)")
    b.bullet("Eminence APT 80 \u2014 compression-driver supertweeter (PA hardware squeezed into a domestic bookshelf cabinet)")
    b.bullet("CIARE 1.26 TW \u2014 Italian bullet tweeter")
    b.bullet("Celestion TF-0510 \u2014 tested for fit, successful")
    b.para(
        "The result: Tannoy Mercury M20 cabinets, gutted, fitted with professional PA drivers, "
        "and sent back into domestic service. Franken-speakers in the truest sense."
    )

    b.heading("The Chamber System (Current)", 2)
    b.para(
        "The satellite speakers that finally worked. Creative T3250W (mains-powered, "
        "~20 years old, class AB IC amps) retained for its subwoofer and electronics; "
        "its original plastic satellites replaced with hand-built 1-litre sealed enclosures "
        "housing Faital Pro 3FE25 professional full-range drivers (3\u201d, 91 dB/W/m, "
        "copper-cap motor, 19mm aluminium voice coil). Music source: laptop via Bluetooth A2DP."
    )
    b.para("Measured March 2026 \u2014 see ")
    b.text("Audio Lab: State of Play March 2026",
           link="https://docs.google.com/document/d/TODO/edit")
    b.text(" for full acoustic measurement results.\n")
    b.para("")

    # === THE SUBWOOFER ===
    b.heading("The Subwoofer", 1)

    b.heading("The Concrete Box \u2014 \u00a3115 Build", 2)
    b.para(
        "The centrepiece of the room system. A sealed subwoofer enclosure built from "
        "concrete slabs, housing a Celestion TF1525 (15\u201d, 250W program, 8\u03a9, "
        "\u00a370 from Lean Business)."
    )
    b.para(
        "Port tuning: target Fb \u2248 50 Hz. Extensive calculations for 85L enclosure "
        "with ports of 6, 8, and 10 cm diameter \u2014 Pringles tubes (8 cm) and soup cans "
        "(7.5 cm) among the materials considered. Currently sealed and too large (low Qtc, "
        "lean bass); porting is planned."
    )
    b.para("Room modes in the 5\u00d74\u00d73m room:")
    b.bullet("34 Hz (5m length)")
    b.bullet("43 Hz (4m width \u2248 double bass open E)")
    b.bullet("57 Hz (3m height)")
    b.bullet("Triple axial coincidence at 171.5 Hz \u2014 all three dimensions produce a mode simultaneously")
    b.para("")

    # === CROSSOVERS AND FILTERS ===
    b.heading("Crossovers and Filters", 1)

    b.heading("Analog: DROK NE5532 Low-Pass Filter", 2)
    b.para(
        "A small PCB with twin-pot for frequency, single-pot for gain, "
        "onboard voltage regulator. It worked, with one persistent problem: "
        "hum at medium gain levels (PSU/EMI). "
        "Also studied: Sallen-Key topologies, 4th-order Butterworth cascades "
        "(1k/3nF, 1.2k/2nF, 3.9k/680pF)."
    )

    b.heading("Digital: PulseAudio Crossover Rack", 2)
    b.para(
        "A PulseAudio-based digital crossover writing a LADSPA filter chain "
        "to ~/.config/pulse/default.pa. Worked but had quirks: mono output caused "
        "input insensitivity, 2-output configuration caused audio looping. "
        "Suspected LADSPA/PulseAudio version mismatch (v15.0)."
    )

    b.heading("Digital: Ecasound", 2)
    b.para(
        "The more serious option. Ecasound with LADSPA plugins (ACDf filter, "
        "1st/2nd order) enables a proper 2-way active crossover with phase alignment "
        "and PA delay compensation. Routes a stereo signal through separate woofer "
        "and tweeter filter chains to a 5.1 ALSA device, each on the correct channel pair."
    )

    b.heading("Op-Amp Selection", 2)
    b.para(
        "The filter modules drew considerable attention to op-amp selection for "
        "the analog crossover path. NE5532 was the standard; alternatives were researched "
        "but NE5532 remained the workhorse."
    )
    b.para("")

    # === BEDSIDE SYSTEM ===
    b.heading("The Bedside System", 1)

    b.heading("Mk 1 \u2014 The Switch Box", 2)
    b.para(
        "A simple DIY audio routing box with miniature DPST slider switches "
        "for selecting between sources (radio, phone) and destinations (headphones, speakers). "
        "Built on PCB-mount hardware with flying lead inputs. Functional, understated, "
        "successful enough to inspire something more ambitious."
    )

    b.heading("Mk 2 \u2014 The Integrated Bedside Table", 2)
    b.para("Planned integration of:")
    b.bullet("PiRadio + Pi alarm/clock audio")
    b.bullet("Pi multi-colour clock display")
    b.bullet("LED reading light")
    b.bullet("Flat audio amplifier")
    b.bullet("Pi-controlled audio routing (source switching, volume via PWM over I2C)")
    b.para(
        "Audio switching IC: TS5A3357DCUTG4 (SP3T, 42p from Farnell) or dual SP4T (92p). "
        "GPIO buttons on pins 3, 5, 7, 11. Construction: modular tile-based on "
        "papier-m\u00e2ch\u00e9 base. Status: planned, component list developed."
    )
    b.para("")

    # === SOFTWARE AND THE PI ===
    b.heading("Software and the Pi", 1)
    b.para(
        "PulseAudio Crossover Rack ran on a Raspberry Pi, routing audio from a Chromecast "
        "via a USB soundcard to the Quad 303. The CM106/CM108/CM109 USB audio chipsets "
        "(C-Media Electronics) were the Pi\u2019s audio interface \u2014 and the source of "
        "considerable debugging, particularly USB drop-outs under load and PulseAudio\u2019s "
        "refusal to handle 8-channel output properly."
    )
    b.para(
        "By 2023 the architecture had settled on: Chromecast \u2192 RPi \u2192 USB soundcard "
        "\u2192 2.1 analog output \u2192 subwoofer filter \u2192 Quad 303. "
        "Crossover frequency: ~303 Hz."
    )
    b.para("audiolab (Python, 2026) superseded much of this with proper measurement infrastructure. See ")
    b.text("audiolab repo", link=REPO_URL)
    b.text(".\n")
    b.para("")

    # === WHAT'S STILL ON THE BENCH ===
    b.heading("What\u2019s Still On the Bench", 1)
    b.bullet("Rega Ela \u2014 tweeter and bass driver replacements needed (Scan-Speak D2008/8511, RR125)")
    b.bullet("Subwoofer porting \u2014 Celestion TF1525 in concrete box, currently sealed and lean. Port at Fb \u2248 50 Hz")
    b.bullet("T/S parameters \u2014 impedance jig measurements on the 15\u201d driver for port and crossover design")
    b.bullet("Tannoy crossover \u2014 franken-speaker cabinets need proper crossover work for the new drivers")
    b.bullet("Bedside Mk 2 \u2014 the integrated Pi/audio/clock/light unit. Design done; needs building")
    b.bullet("Yamaha AX-396 \u2014 retrieve from loft")
    b.para("")

    # Footnote
    footnote(b)

    print(b.build_json())


if __name__ == "__main__":
    main()
