#!/usr/bin/env python3
"""Build batchUpdate JSON for the cld: Audio Hi-Fi Contents GDoc.

Generates Google Docs API requests for the contents page that mirrors
audiolab/docs/contents.md — linking GDocs, repo files, and Claude Chats.

Usage:
    python3 build_gdoc.py | gws docs documents batchUpdate \
        --params '{"documentId": "1GaR40JKOdqkrsCA43CJzVk150432IWvjQwY9rVnIlZ4"}' \
        --json "$(cat)"
"""

import subprocess
import sys
from datetime import date
from pathlib import Path

# Import DocBuilder from gcp repo
sys.path.insert(0, str(Path.home() / "gcp" / "lib"))
from docbuilder import DocBuilder

DOC_ID = "1GaR40JKOdqkrsCA43CJzVk150432IWvjQwY9rVnIlZ4"
REPO_URL = "https://github.com/PeterGrecian/audiolab"


def get_commit_hash():
    return subprocess.check_output(
        ["git", "rev-parse", "HEAD"], text=True
    ).strip()


def repo_entry(b, path, desc):
    url = f"{REPO_URL}/blob/main/{path}"
    if path.endswith("/"):
        url = f"{REPO_URL}/tree/main/{path.rstrip('/')}"
    b.text("  ")
    b.text(path, link=url)
    b.text(f" — {desc}\n")


def footnote(b):
    commit = get_commit_hash()
    short = commit[:7]
    today = date.today().strftime("%-d %B %Y")
    commit_url = f"{REPO_URL}/commit/{commit}"

    b.text("Generated by Claude Code on ", italic=True)
    b.text(today, italic=True)
    b.text(". Source: ", italic=True)
    b.text("audiolab", italic=True, link=REPO_URL)
    b.text(" @ ", italic=True)
    b.text(short, italic=True, link=commit_url)
    b.text(".\n", italic=True)


def main():
    b = DocBuilder()

    b.title("Audio Hi-Fi Contents")

    b.para(
        "Index of audio hi-fi documents across Google Drive, GitHub, and Claude Chat. "
        "Covers speakers, amplifiers, crossovers, DSP, acoustic measurement, and the "
        "audiolab measurement tool.",
        italic=True
    )
    b.para("")

    # === This Repo ===
    b.heading("This Repo — audiolab", 1)

    repo_items = [
        ("docs/contents.md", "This file's GitHub mirror"),
        ("docs/acoustic_workflow.md", "Measurement workflow: impedance → free-field → in-room → correction"),
        ("docs/chamber_hifi.md", "Chamber hi-fi acoustic measurements and characterisation"),
        ("docs/dynamic_range.md", "Dynamic range and noise floor notes"),
        ("docs/gdrive/", "Cached markdown copies of Google Drive audio documents"),
        ("audiolab/", "Python measurement tool — devices, capture, analysis, generator, curses UI"),
        ("calibrate_mic.py", "Microphone calibration script"),
    ]
    for path, desc in repo_items:
        repo_entry(b, path, desc)

    b.para("")

    # === Google Drive sections ===
    b.heading("Google Drive — Audio Hi Fi", 1)

    sections = {
        "Canonical": [
            ("Hi-Fi History — Speakers, Amps and Franken-Builds", "1JQBM-bsIsSDth-TVEmkEuBrYjS8Xj4ZB2W8xow5dWWw", "Mar 2026"),
            ("Audio Lab: State of Play March 2026", None, "Mar 2026"),
        ],
        "Speakers": [
            ("speaker renovation", "1jkZuoww2KrWdb3vJq1ciZMlTcntQ_vMUs4L4S9cuDqQ", "2014–2018"),
            ("Rega Ela restoration", "1pHdhUebXidxmZGD54jqHcOhq92lu0KrTsJ06Ya4nA1M", "2017"),
            ("DIY speaker plan", "1dEv1H6-Ii3s0onigkjS8D6xObMUsGmpIUj8FBbV3pQA", "2017"),
            ("slab concrete enclosures", "1zs5zTdgPc-7X--qKAqlPZo6A9AeOl7UxULQ6fDxzcCE", "2017"),
            ("castings", "127Im6BjUFR3x1m1fHtDznu9rvOOUqd7xSQ1wK7UIPoU", "2017–2018"),
            ("full range single speaker + sub", "19bFchoGs9IpsHCGnFTetzQGB1LLi67AJRDa8bC4vTIM", "2023"),
            ("speaker design", "1kTL_uXTt4Syg6ABqtVX9wZBlRWFX2g1ZVO0fOb-Xy4Y", "2023"),
            ("acoustic simulation for speaker design", "1no-siA1LZ7UZCvKKfQ5dXRTXonbPAX16C0KBhc7nLbY", "2017"),
        ],
        "Amplifiers": [
            ("amps", "1B3Q75sq605bBWVzx4b_vrx3smacGb350nBnOfmOkiVY", "2017–2020"),
            ("audio power amplifier design", "1KlTarCmwIfdkqcfjwJ0cYed1xEahftWzYb1AS0xzdGc", "2018"),
            ("audio power amplifier design (2024)", "191OC0kHmKSuQkJ6VSe7ZiGQ3M1XSSyhv8tRt659n4rU", "2024"),
            ("TPA3116D2 board", "1dYgnu4n4El55CG90WS3OWO5mZwlbRVT9m2SwffQx9Ro", "2017–2020"),
            ("TDA7498", "1Giq7yCayz7TH447k_l4Gt9xAb0OhHNO-7dwugjQx9W4", "2017"),
        ],
        "Crossovers and DSP": [
            ("DROK Subwoofer lowpass filter NE5532", "1v8cNY5fY-Kp355gv3CBV8rXN2gmLeKQHxMi2kHivIO8", "2017–2018"),
            ("Low Pass filter episode", "1BVfzC6OAj2H1bDMB8iKvLozjZt08j4kjiJArzp4lU_4", "2018"),
            ("LP filter 2nd order design", "1iFK6Weq3EMLJUmMvTX8fGx9KIwpGMIiUT9AwYeY24wg", "2018"),
            ("pyo xover", "1Mkvx8geAZSdGUCbVicAgz5BXV-mP5Qibkvu484kvSyA", "2017–2018"),
            ("sox cookbook", "1Iu6yvV62mtlcGP3OM5aJ0ZETzlkoRbwTNbjLhbUP2L8", "2017"),
            ("pulse audio", "1qiTni-F7BYUwZbDU-6mi6pYQGWQ2K7uPs7r4rAqUQV4", "2023"),
            ("RPi audio 2023", "1Kb3HSkitFtxotCia_5xRwvDODpVj3Jd-wR2WJ6UYihM", "2023"),
            ("Hifi 2023", "1hOuTlIGV1EBWLDct30xxB3X57ZjxdxEVY1qeCmdVa9I", "2023"),
        ],
        "References and Misc": [
            ("accoustics references", "1LtTCjJknNaMGOLaRnjljPrH6WZlJ4GFZZUybnOVHuB8", "2017"),
            ("experiments in audio bandcamp pytone sox", "10KIzMrTpeB4DFZjowVZ8sO8JaBCrBuzNvvEEkJdfa9Q", "2017"),
            ("sources, mixing desk", "1TZLPE-J2mZeiOM-JosGGf3ro8MSmK_au-xeZDvl6PPk", "2017"),
            ("Audio todo", "1i_x5uBxwyB-esTeV0VhHuNUdzWQMvrswlryE01Z6DK4", "2018"),
            ("TODO list: Music room and Hi Fi", "1qNTQ9S5Eah0NdSfhHDSz_nJrjVA6ixH5PpH2Jy0kztY", "2017"),
        ],
        "Spin-offs": [
            ("windows audio", "1CdakJu5NjbLh6j1hh2uRRwe1gVLbzUcI-VTIzpdsl6Y", "2025"),
            ("android audio", "1c8W7O2q12H3LN0CoCRbW3hOG_eQ2hW1-TzNvSiCVy60", "2024"),
            ("solar audio", "1SbusGQDdp921mQtMuuDXBU6U9vghY8aM3cqLxO2YYTI", "2025"),
            ("rx8 audio fault", "1mq2RVOM3LV67hEmclTXuJxkL5wY7SKXoWa3qqGpC6a4", "2023"),
        ],
    }

    for section, items in sections.items():
        b.heading(section, 2)
        for title, doc_id, date_str in items:
            b.gdoc_entry(title, doc_id, date_str)

    b.para("")

    # === Claude Chats ===
    b.heading("Related Claude Chats", 1)

    chats = [
        ("Building a digital audio crossover / CamillaDSP",
         "https://claude.ai/chat/e63125db-3a23-4981-8f4b-2a9751c7c509",
         "Triamp topology, Franken-ELA, room acoustics"),
        ("Chamber hifi characterisation, gdrive mount",
         "https://claude.ai/chat/6c026edd-58e7-4ecd-a29c-88f42655d936",
         "3FE25 measurements, 15dB notch at 6-7kHz, GDocs architecture"),
        ("Pedagogical audio power amplifier",
         "https://claude.ai/chat/8a53ccb8-73d5-450f-abd3-407ad6d8714e",
         "KiCad Class AB amp, Shostakovich silkscreen, thermal bias"),
        ("Measuring subwoofer driver excursion",
         "https://claude.ai/chat/ed1a8546-eb93-4265-a7c7-5c2f105ab8a3",
         "APT80 sensitivity, triamp power, CamillaDSP Pi3+CM106"),
        ("Hi-Fi History POC / knowledge architecture",
         None,
         "Contents page, RAG, chat → GDocs → GitHub pipe"),
    ]

    for title, url, topics in chats:
        if url:
            b.text(title, link=url)
        else:
            b.text(title)
        b.text(f" — {topics}\n")

    b.para("")

    # Footnote
    footnote(b)

    print(b.build_json())


if __name__ == "__main__":
    main()
